---
- name: Install common packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - screen
    - vim
    - telnet
    - tcpdump
    - supervisor
    - wget
    - curl
    - munin
    - munin-node
